[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/gdrive"
  to = "/.netlify/functions/gdrive"
  status = 200

[[redirects]]
  from = "/api/drive"
  to = "/.netlify/functions/gdrive"
  status = 200
